---
title: "Clinical notes: dementia caused by intracranial tuberculoma"
author: "Green Ear Rabbit"
date: "04/06/2020"
output: html_document
---

Tuberculosis is not only a disease in respiratory systems, it can infect many organs, for example, osseous tuberculosis, Intra-abdominal Tuberculosis and central nervous system .

I saw one case of intracranial tuberculoma during my observation in Dept.TB. The patient have kind of cognitive decline, and there is several seconds delay when he answer people's questions, come to hospital because disability of one leg. Then he was diagnosed as intracranial tuberculosis with TB after CT and a series of serum test.

This is my first time to know intracranial tuberculoma, I begin to search some information and try to improve my knowledge.

Intracranial tuberculoma is a type of central nervous system tuberculosis (TB), which also include tuberculous meningitis and spinal tuberculous arachnoiditis

Here is a nice link to help you know intracranial tuberculoma

[Overview guide from Science Direct] (https://www.sciencedirect.com/topics/medicine-and-dentistry/intracranial-tuberculoma)


