---
title: 'My clinical notes 3: A schizophrenia patient'
author: "Green Ear Rabbit"
date: "25/05/2020"
output: html_document
---

One good weather day afternoon I sit in the public office and read a doctor's book sleeply. 

There is a new patient just accepted by the department. It's a patient with schizophrenia, with liver cirrhosis, and were sent to hospital by apsychia.

Considering schizophrenia, he was put in a seperate and isolated ward.

I am just a student, and what I can do is only to go to ask patient's history. 

...
...
...
...
...
I feel very sorry to hear this patient history, even if I am not supposed to be so. I also wanted to say some encourage words, but I don't know what to say.

I don't want to describe this story. But I want to talk something about mental illness:

He is not local people in this city, neither for toursim. He was from relief house. He wanted to find a job here, but cannot find a long term job even if he can do lots of labors. He is literate and speaking is also clear.  

He did not have any abnormal behavoral even if he has schizophrenia. At begining he was put into a seperate ward and later we found it's unnecessary and he's totally a normal patients.

He said, schizophrenia, can be aggressive or just depressive, he is the later one. As he decribed, he never had any aggressive behavior.

However, why did the psychiatrist diagnse him as schizophrenia eight years ago, rather than just depression? Will the society, the factory accept a patient with schizophrenia?

I think the psychiatrist should be careful to give any diagnosis of mental disorder. I always against the over-diagnosis in mental health. Does ADHD a real disease? Does depression a real disease? Or even, does schizophrenia a real disease? I don't think so. For ADHD, it's just not same as other children. For depression, bipolor and schizophrenia, it's just a status. 

Also, one diagnosis mental disorder, it becomes a label. As this patient, even if he don't have any aggressive behavor, he may have difficult to find a job because his schizophrenia and have a better life.


