---
title: "Clinical notes: Health Disparities"
author: "Wanqi"
date: 2020-11-28T21:13:54-06:00
categories: ["R"]
tags: ["intracranial tuberculoma", "public health", "health disparities"]
output:
  html_document:
    df_print: paged
mainfont: Palatino
fontsize: 13pt
subtitle: The characteristics of the COVID-19 outbreak in United States
always_allow_html: yes
---


People in low-socioeconomic status are at a high risk of diseases and death. I saw two patients both diagnosed with intracranial tuberculoma. One of them was a middle-aged and high-income man. He lived in a VIP ward for three months. He even wanted to live in the ward for several more days, after the doctors said that he is fully recovered. The other one is a 19-year-old rural boy, he came to city alone for a higher salary work. He came to the hospital too late, and had shown cognitive decline and disability in one leg at the time of diagnosis. His condition did not turn good at the time I left the hospital. I cannot forget the two patients for a long time, and I believed that, as public health workers and researchers, we have the duty to call for doctors and policy-makers' attention to reduce such health disparities. 