<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.69.1" />


<title>An exploration of patient infomation of COVID in South Korea - My assignments at school  - A Hugo website</title>
<meta property="og:title" content="An exploration of patient infomation of COVID in South Korea - A Hugo website">


  <link href='https://green-ear-rabbit.github.io/blog/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/blog/css/fonts.css" media="all">
<link rel="stylesheet" href="/blog/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/blog/" class="nav-logo">
    <img src="/blog/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/blog/about/">About</a></li>
    
    <li><a href="https://github.com/rstudio/blogdown">GitHub</a></li>
    
    <li><a href="https://twitter.com/rstudio">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">10 min read</span>
    

    <h1 class="article-title">An exploration of patient infomation of COVID in South Korea</h1>

    
    <span class="article-date">0001-01-01</span>
    

    <div class="article-content">
      
<script src="/blog/rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="/blog/rmarkdown-libs/jquery/jquery.min.js"></script>
<link href="/blog/rmarkdown-libs/datatables-css/datatables-crosstalk.css" rel="stylesheet" />
<script src="/blog/rmarkdown-libs/datatables-binding/datatables.js"></script>
<link href="/blog/rmarkdown-libs/dt-core/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="/blog/rmarkdown-libs/dt-core/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="/blog/rmarkdown-libs/dt-core/js/jquery.dataTables.min.js"></script>
<link href="/blog/rmarkdown-libs/crosstalk/css/crosstalk.css" rel="stylesheet" />
<script src="/blog/rmarkdown-libs/crosstalk/js/crosstalk.min.js"></script>


<pre class="r"><code>require(tidyverse)
require(ggplot2)</code></pre>
<div id="overview-of-assignment-requirement" class="section level1">
<h1>Overview of assignment requirement</h1>
<p>VisualizationofdataingraphicalformatusingR.Submission deadline: 2020-03-23 14:00 (5% of final mark, no re-sit)</p>
<ul>
<li>Obtain a public health dataset (different from Assignment 1, from published papers, government websites, or your own research) that is suitable for producing graphs.</li>
<li>Import the dataset into an R project in an R markdown report.</li>
<li>Plot three of the following graphs with the dataset in the report:scatterplot, pie chart, bar graph, and box graph. For the scatter plot, please provide a linear regression, list the intercept, slope, and the correlation coeﬀicient using R. For the box graph, please add the mean value to each box.</li>
<li>Knit the .Rmd file into a .pdf report.</li>
<li>Submit the data file, the R markdown file (.Rmd), the report file (.pdf), and the project file (.Rproj).</li>
</ul>
</div>
<div id="my-research-topic" class="section level1">
<h1>My research topic</h1>
<p>COVID-19 has rapidly become a worldwide pandemic since December in 2019, with the symtoms of fever, cough, fatigue, and clinic manifestation of maniground-glass lung changes, hypoxaemia, and deranged gastrointestinal, liver and renal function<span class="citation">(<span class="citeproc-not-found" data-reference-id="chan_familial_2020"><strong>???</strong></span>)</span>. For severe cases, the disease will deteriorate to severe fibrotic lung (which is called “Withe Lung” by Chinese doctors), and multi-organ failure <span class="citation">(<span class="citeproc-not-found" data-reference-id="cao_trial_2020"><strong>???</strong></span>)</span>.</p>
<p>Moreover, the virus has a high reproductive number (R<sub>0</sub>). Due to the R<sub>0</sub> and be influenced by multi-factors including population density and temporal policy or laws, there is no extract and international consensus R<sub>0</sub> published. But up to know, we can see that at early stage of transmission, R<sub>0</sub> is around 3.6~4.0<span class="citation">(<span class="citeproc-not-found" data-reference-id="read_novel_2020"><strong>???</strong></span>)</span>, which is higher than seasonal flu (~1.2) and swine flu (~1.2-1.6)<span class="citation">(<span class="citeproc-not-found" data-reference-id="read_novel_2020"><strong>???</strong></span>)</span>.</p>
<p>Due to the rapid transimission of disease and relatively high fatality, it has become a emergency problem worldwide. Some early infected countries e.g., Japan and South Korea, have published open datasets to researches worldwide.</p>
<p>KCDC (Korea Centers for Disease Control &amp; Prevention) announces that the information of COVID-19 quickly and transparently, and published a dataset for annoymous patient infomation. They also published some most simple and basic visulization of sociodemographic characteristic of patients, simple bars and simple pies. However, the visualization is deficient, less informed and less artistic. Click <a href="https://www.kaggle.com/kimjihoo/coronavirusdataset">here</a> to download the whole dataset published on by KCDC.</p>
<p>This brief report will provide more informed and artistic visuliation and analysis than availiable results on <a href="https://www.kaggle.com">Kaggle</a> to download the whole dataset. Given the current condition in Korea, we mainly focus on three research questions:</p>
<ul>
<li>Is there any relationship between age and the number of contacted people from infection to isolated?</li>
<li>Is there any cluster transmission of disease, e.g.,religious group, as <a href="%22https://www.bbc.com/news/world-asia-51603251%22">news</a> reported.</li>
<li><p>How is the cases distributed in each province?
# Create a R project and input data
I created a R project floder and a .Rproj file in it. Moreover, it has been connected to github, however, according to the university policy, this repositary in github will not be available in public until the submission deadline.</p></li>
<li>Floder name: DPH206_A2</li>
<li>R project name: DPH206_A2.Rproj</li>
<li><p>Github repositary name: Wanqi-Wang/DPH206_A2</p></li>
</ul>
<pre class="r"><code>ds&lt;-readr::read_csv(&quot;data/patientinfo.csv&quot;)</code></pre>
<pre class="r"><code>dim(ds)</code></pre>
<pre><code>## [1] 2218   18</code></pre>
<p>The dataset has 2218 rows (objectives) and 18 columns (variables). To save computing time, <strong>Table 1</strong> Provide a brief look at the first ten rows of the dataset.</p>
<pre class="r"><code>DT::datatable(ds[c(1:10),],caption = &quot;Table 1. A brief look at first 10 rows of the dataset of COVID outbreak in South Korea&quot;)</code></pre>
<div id="htmlwidget-1" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"filter":"none","caption":"<caption>Table 1. A brief look at first 10 rows of the dataset of COVID outbreak in South Korea<\/caption>","data":[["1","2","3","4","5","6","7","8","9","10"],[1000000001,1000000002,1000000003,1000000004,1000000005,1000000006,1000000007,1000000008,1000000009,1000000010],[2,5,6,7,9,10,11,13,19,21],["male","male","male","male","female","female","male","male","male","female"],[1964,1987,1964,1991,1992,1966,1995,1992,1983,1960],["50s","30s","50s","20s","20s","50s","20s","20s","30s","60s"],["Korea","Korea","Korea","Korea","Korea","Korea","Korea","Korea","Korea","Korea"],["Seoul","Seoul","Seoul","Seoul","Seoul","Seoul","Seoul","Seoul","Seoul","Seoul"],["Gangseo-gu","Jungnang-gu","Jongno-gu","Mapo-gu","Seongbuk-gu","Jongno-gu","Jongno-gu","etc","Songpa-gu","Seongbuk-gu"],[null,null,null,null,null,null,null,null,null,null],["overseas inflow","overseas inflow","contact with patient","overseas inflow","contact with patient","contact with patient","contact with patient","overseas inflow","overseas inflow","contact with patient"],[1,1,2,1,2,3,3,1,2,3],[null,null,2002000001,null,1000000002,1000000003,1000000003,null,null,1000000003],[75,31,17,9,2,43,0,0,68,6],["2020-01-22",null,null,"2020-01-26",null,null,null,null,null,null],["2020-01-23","2020-01-30","2020-01-30","2020-01-30","2020-01-31","2020-01-31","2020-01-31","2020-02-02","2020-02-05","2020-02-05"],["2020-02-05","2020-03-02","2020-02-19","2020-02-15","2020-02-24","2020-02-19","2020-02-10","2020-02-24","2020-02-21","2020-02-29"],[null,null,null,null,null,null,null,null,null,null],["released","released","released","released","released","released","released","released","released","released"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>patient_id<\/th>\n      <th>global_num<\/th>\n      <th>sex<\/th>\n      <th>birth_year<\/th>\n      <th>age<\/th>\n      <th>country<\/th>\n      <th>province<\/th>\n      <th>city<\/th>\n      <th>disease<\/th>\n      <th>infection_case<\/th>\n      <th>infection_order<\/th>\n      <th>infected_by<\/th>\n      <th>contact_number<\/th>\n      <th>symptom_onset_date<\/th>\n      <th>confirmed_date<\/th>\n      <th>released_date<\/th>\n      <th>deceased_date<\/th>\n      <th>state<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,4,11,12,13]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="rq1-is-there-any-relationship-between-age-and-the-number-of-contacted-people-from-infection-to-isolation" class="section level1">
<h1>RQ1: Is there any relationship between age and the number of contacted people from infection to isolation</h1>
<p>The reason of why did I interest in this research question is that, previous studies shown that people with younger or middle age may have more contact with others. Moreover, people in such age are realtively strong and more likely to work or continue daily activity after some mild symtoms onset. Following analysis will analyze that if younger people has more contacted people from infection to isolation.</p>
<ul>
<li>The “age” variable in dataset are rounded to numbers like “30s”, “40s”, I think we might lose information for this rounded age, so let’s calculate the accurate age by birth year of participants</li>
</ul>
<pre class="r"><code>str(ds$birth_year)</code></pre>
<pre><code>##  num [1:2218] 1964 1987 1964 1991 1992 ...</code></pre>
<pre class="r"><code>ds$trueage&lt;-2020-ds$birth_year
range(ds$trueage, na.rm = TRUE)</code></pre>
<pre><code>## [1]   0 104</code></pre>
<pre class="r"><code>ds$agegroup=cut(ds$trueage, breaks = seq(0,110, by = 10), right = FALSE,labels = c(&quot;0-10&quot;,&quot;10-20&quot;,&quot;20-30&quot;,&quot;30-40&quot;,&quot;40-50&quot;,&quot;50-60&quot;,&quot;60-70&quot;,&quot;70-80&quot;,&quot;&gt;80&quot;,&quot;&gt;80&quot;, &quot;&gt;80&quot;))</code></pre>
<ul>
<li>The “contact_number” means the number of people this person had contaced from infected to isolated. There is 1807 of them whose contact number is unknown, but we still have 411 observations.</li>
</ul>
<pre class="r"><code>summary(ds$contact_number, na.rm=TRUE)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    0.00    2.00    5.00   24.13   16.00 1160.00    1807</code></pre>
<pre class="r"><code>range(ds$contact_number, na.rm = TRUE)</code></pre>
<pre><code>## [1]    0 1160</code></pre>
<ul>
<li>Create a analysis sample for RQ1.</li>
</ul>
<pre class="r"><code>dst&lt;-subset(ds,!is.na(ds$contact_number)&amp; !is.na(ds$trueage))</code></pre>
<ul>
<li>Make a pilot visuliation to see if there is any relationship between age and contacted number</li>
</ul>
<pre class="r"><code>lm1&lt;-lm(dst$contact_number~dst$trueage)
sqrt(summary(lm1)$r.squared)</code></pre>
<pre><code>## [1] 0.003548554</code></pre>
<pre class="r"><code>plot(dst$trueage, dst$contact_number, pch = 16, 
     col=ifelse(dst$contact_number &gt; mean(dst$contact_number),ifelse(dst$contact_number&gt;mean(dst$contact_number)+2*sd(dst$contact_number),&quot;red&quot;,&quot;yellow&quot;), &quot;green&quot;), xlim = c(0, 120), ylim = c(0, 1200), xlab = &quot;Age of participants&quot;, ylab = &quot;contact number from infected to isolated&quot;, main= &quot;Figure 1: Distribution of contacted number across age&quot;, sub = &quot;Note: Analysis sample N=322&quot;,las = 1) 
abline(h = mean(dst$contact_number)+2*sd(dst$contact_number), col=&quot;red&quot;) 
abline(h = mean(dst$contact_number), col=&quot;blue&quot;)
abline(lm1,col=&quot;black&quot;)
text(80,mean(dst$contact_number)+ 40, labels = &quot;mean of contact number&quot;)
text(20,50, labels = &quot;y=25.12-0.02x, r=0.0035&quot;)
text(80,mean(dst$contact_number)+2*sd(dst$contact_number)+40, labels = &quot;mean+2SD of contact number&quot;)
text(x=dst$trueage, y=dst$contact_number+ 40, labels=ifelse(dst$contact_number&gt;mean(dst$contact_number)+2*sd(dst$contact_number),dst$contact_number,&quot;&quot;), col=&quot;red&quot;) </code></pre>
<p><img src="/blog/post/2020-5-21-My-assignments-in-school-Data-visualization_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>As you see, in this scatter plot, some points are higher than mean+2SD. Moverover, due to the large y limit of plot, we cannot clearly distinguish liner regression line and the horizontal line of mean. Thereby, I would remove “extreme point” and plot again, however, definately we cannot remove “extreme point” by the point higher than mean+2SD, becasue the contacted number, this variable, may not be normally distributed. Let’s test it!</p>
<ul>
<li>Produce a curve to see if the contacted number of patients are normally distributed.</li>
</ul>
<pre class="r"><code>library(&quot;ggpubr&quot;)
ggdensity(dst$contact_number, 
          main = &quot;Figure 2: Density plot of contact_number of patients&quot;,
          xlab = &quot;Number of contacted people from infection to isolation&quot;)</code></pre>
<p><img src="/blog/post/2020-5-21-My-assignments-in-school-Data-visualization_files/figure-html/unnamed-chunk-10-1.png" width="672" />
Clearly shown in <strong>Figure 2</strong>, it’s not a normal distribution. So we cannot pick up outliers by traditional statistical methods used in normal distribution. Let’s use boxplot! A boxplot was used to detect outliers and display heterogeneity of distribution and effects of explanatory variables.</p>
<ul>
<li>Let’s make a boxplot for each age group, to detect outliers of contacted number</li>
</ul>
<pre class="r"><code>boxplot(dst$contact_number~dst$agegroup,
main=&quot;Figure 3: Boxplots of contacted number across age group&quot;,
sub = &quot;Analysis sample N=322&quot;,
xlab=&quot;Age group&quot;,
ylab=&quot;Note: Number of contacted people from infection to isolation&quot;,
col=rainbow(9),
border=&quot;brown&quot;
)</code></pre>
<p><img src="/blog/post/2020-5-21-My-assignments-in-school-Data-visualization_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Let’s create a better boxplot</p>
<pre class="r"><code>boxplot(dst$contact_number~dst$agegroup,
main=&quot;Figure 4: Contacted number across age group (outliner removed)&quot;,
sub = &quot;Note: Analysis sample N=253&quot;,
xlab=&quot;Age group&quot;,
ylab=&quot;Number of contacted people from infection to isolation&quot;,
col=rainbow(9),
border=&quot;brown&quot;, outline=FALSE
)
outliers &lt;- boxplot(dst$contact_number~dst$agegroup, plot=FALSE)$out
means &lt;- by(dst[-which(dst$contact_number %in% outliers),]$contact_number, dst[-which(dst$contact_number %in% outliers),]$agegroup, mean) 
points(means, col = &#39;black&#39;, pch = 17)</code></pre>
<p><img src="/blog/post/2020-5-21-My-assignments-in-school-Data-visualization_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<ul>
<li>Let’s exclude outliers and re-plot a scatter plot and its linear trend.</li>
</ul>
<pre class="r"><code>dst2&lt;-dst[-which(dst$contact_number %in% outliers),]
range(dst2$contact_number)</code></pre>
<pre><code>## [1]  0 68</code></pre>
<pre class="r"><code>lm2&lt;-lm(dst2$contact_number~dst2$trueage)
sqrt(summary(lm2)$r.squared)</code></pre>
<pre><code>## [1] 0.05680231</code></pre>
<pre class="r"><code>plot(dst2$trueage, dst2$contact_number, pch = 16, col = &quot;green&quot;, xlim = c(0, 110), ylim = c(0, 70), xlab = &#39;Age of participants&#39;, ylab = &#39;Contact number from infected to isolated&#39;, main = &quot;Figure 5: Distribution of contacted number across age (outliers excluded)&quot;, sub = &quot;Note: Analysis sample N=253&quot;, las = 1) 
abline(lm2, col=&quot;black&quot;) 
text(90, 12,&quot;y=8.00-0.02x, r=0.057&quot;)</code></pre>
<p><img src="/blog/post/2020-5-21-My-assignments-in-school-Data-visualization_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<ul>
<li>Produce a quantile-quantile plot of the residuals to test for the normality of residuals</li>
</ul>
<pre class="r"><code>dst2$RESID &lt;- resid(lm2)
qq &lt;- ggplot(dst2, aes(sample=RESID)) +
    stat_qq() +
    stat_qq_line() +
    ggtitle(&quot;Figure 6: Quantile-quantile plot of residuals&quot;)
qq</code></pre>
<p><img src="/blog/post/2020-5-21-My-assignments-in-school-Data-visualization_files/figure-html/unnamed-chunk-15-1.png" width="672" />
Accoding to the qqplot shown in <strong>Figure 6</strong>, personally feeling, the residuals are mainly normally distributed. Thereby, I assume that a simple linaer regression is acceptable.</p>
</div>
<div id="rq2-is-there-any-cluster-transmission-of-disease-e.g.religious-group" class="section level1">
<h1>RQ2: Is there any cluster transmission of disease, e.g.,religious group?</h1>
<pre class="r"><code>dsp &lt;- ds %&gt;% 
     mutate_at(&quot;infection_case&quot;, funs(recode(., &quot;Shincheonji Church&quot;= &quot;Church&quot;,&quot;Onchun Church&quot;= &quot;Church&quot;, &quot;River of Grace Community Church&quot; = &quot;Church&quot;,&quot;Dongan Church&quot;=&quot;Church&quot;,&quot;gym facility in Sejong&quot;=&quot;Gym facility&quot;, &quot;gym facility in Cheonan&quot;=&quot;Gym facility&quot;, &quot;Suyeong-gu Kindergarten&quot;=&quot;Apartment &amp; Kindergardem&quot;, &quot;Seongdong-gu APT&quot;=&quot;Apartment &amp; Kindergardem&quot;, &quot;Cheongdo Daenam Hospital&quot;=&quot;Hospital &amp; Government agency&quot;, &quot;Eunpyeong St. Mary&#39;s Hospital&quot;=&quot;Hospital &amp; Government agency&quot;, &quot;Guro-gu Call Center&quot;=&quot;Hospital &amp; Government agency&quot;, &quot;Ministry of Oceans and Fisheries&quot;=&quot;Hospital &amp; Government agency&quot;, &quot;Pilgrimage to Israel&quot;=&quot;Else&quot;, 
     &quot;etc&quot; =&quot;Else&quot;,&quot;contact with patient&quot;=&quot;Contact with patient&quot;, &quot;NA&quot; =&quot;Unknown&quot;)))
dsp$inf&lt;-as.factor(dsp$infection_case)</code></pre>
<pre class="r"><code>library(&quot;plotrix&quot;)
te&lt;-summary(dsp$inf[!is.na(dsp$inf)])
f3&lt;-pie3D(te,explode=0.05, col=rainbow(7),main = &quot;Figure 7: Pie chart the distribution of suspected infection source (missing value excluded)&quot;)
pie3D.labels(f3,labels=names(te),labelrad=1.8)</code></pre>
<p><img src="/blog/post/2020-5-21-My-assignments-in-school-Data-visualization_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<ul>
<li>Plot a bar graph for each age group</li>
</ul>
<pre class="r"><code>barplot(summary(dsp$inf[!is.na(dsp$inf)]), col=rainbow(7),main = &quot;Figure 8: Bar graph the distribution of suspected infection source (missing value excluded)&quot;)</code></pre>
<p><img src="/blog/post/2020-5-21-My-assignments-in-school-Data-visualization_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Let’s explore if there is some difference for different gender</p>
<pre class="r"><code>table1&lt;-table(dsp$sex,dsp$inf)
barplot(table1, main=&quot;Figure 9: The bar plot for suspected infection source for different age group&quot;,
  xlab=&quot;suspected infection source&quot;,ylab=&quot;Number of patients&quot;, col=c(&quot;pink&quot;,&quot;blue&quot;),
  legend = rownames(table1), beside=TRUE)</code></pre>
<p><img src="/blog/post/2020-5-21-My-assignments-in-school-Data-visualization_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
<div id="rq3-how-is-the-cases-distributed-in-each-province" class="section level1">
<h1>RQ3: How is the cases distributed in each province?</h1>
<p>A bar plot was maded to compare cases across different province, as shown in <strong>Figure 3</strong>.</p>
<pre class="r"><code>ds$pro&lt;-as.factor(ds$province)
summary(ds$pro)</code></pre>
<pre><code>##             Busan Chungcheongbuk-do Chungcheongnam-do             Daegu 
##               101                28               118                63 
##           Daejeon        Gangwon-do           Gwangju       Gyeonggi-do 
##                22                29                18               300 
##  Gyeongsangbuk-do  Gyeongsangnam-do           Incheon           Jeju-do 
##              1054                85                32                 4 
##      Jeollabuk-do      Jeollanam-do            Sejong             Seoul 
##                 7                 4                41               282 
##             Ulsan 
##                30</code></pre>
<pre class="r"><code>barplot(summary(ds$pro), col = rainbow(12), ylim = c(0, 1150), xlab = &#39;Province&#39;, ylab = &#39;Confirmed cases of COVID&#39;, main = &quot;Figure 10: the distribution of COVID cases across South Korea&quot;, density=10,las = 1)</code></pre>
<p><img src="/blog/post/2020-5-21-My-assignments-in-school-Data-visualization_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
<div id="results" class="section level1">
<h1>Results</h1>
<p>As for research question 1, <strong>Figure 1</strong> provide a pilot visulation of age and contacted number, and then I plan to exclude the outliers of contacted number. But we need to see if the contacted number is normal distributed. As shown in <strong>Figure 2</strong>, it’s not a normal distributed. Then I switch age to age group, then make a boxplot and exclude outliers in each age group, as shown in <strong>Figure 3</strong> &amp; <strong>Figure 4</strong>. Later we make a new scatter plot to exclude outliers of each age group (<strong>Figure 5</strong>). Moreover, the normality of linear regression was tested by a quantile-quantile plot (<strong>Figure 6</strong>). From the visulation, we can see that the overall trend is that, by the increasing age, the contacted number of people from infection to isolation is decresed, even if for children and teenagers may be lower from the visualtion. For every one unit increase in age, the number of contacted will decrease 0.02 unit, correlation coefficient is 0.05680231, which is much more better then the model which include outliers (y=25.12-0.02x, r=0.0035). Thereby, yound adults are at a relatively high risk to spread disease, and the suspension of bussness, fatories and colleges is necessary for the infection control. The statistical methods are according to statistical textbook <span class="citation">(<span class="citeproc-not-found" data-reference-id="van_belle_biostatistics_2004"><strong>???</strong></span>)</span></p>
<p>As for research question 2, to visualize the suspected infection source, I first plot a pie chart (<strong>Figure 7</strong>) to see the percentage, but due to the inherited limition of pie chart, which is potential missleading. Thereby, we plot a bar graph (<strong>Figure 8</strong>), we can see that contact with patients takes most of cases, which is consistant with previous research of high R<sub>0</sub>. The hospital and government agency also takes large count, which indicates that the nosocomial infection of COVID contributes to the outbreak of COVID in South Korea, and the disease control in government agency make be suboptimal. Moreover, we make a multiple bar plot for male and female (<strong>Figure 9</strong>), there are 34 female infected by gym facility, while no male reported to be infected at gym facility, which may be considered as a cluster infection in gym facility.</p>
<p>At last, I made <strong>Figure 10</strong> and find that Gyeongsangbuk-do has the most infected cases (n=1054), which is consistant with previous <a href="http://www.korea.net/NewsFocus/Society/view?articleId=182693">news</a>. The government may need to send professional medical and disease control team to Gyeongsangbuk-do, and provide more funding to the province for disease control.</p>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>It’s only an pilot study, several study limitations merit noting. <strong>First</strong>, due to limited varaibles for travel history, co-morbidities, and symtoms, our analysis is relatively weak. <strong>Second</strong>, the generality is limited due to different policy and laws for disease control, different life and diety style between Korea and other counties. <strong>Third</strong>, even if the visulization is relatively aesthetic and colorful, different people may have different subjective opinion of “aesthetic”.</p>
<p>Nevertheless, the report is an exploratory try of Korea COVID outbreak dataset and satisfied well with the assignment requirement, and a clear clue were tried to designed, rather than just make many plots. Both idea and code are finished independently. All relative online source are provided with a link, and all realtive research are provided citation and link-citation reference list.</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/blog/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/blog/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/blog/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

